"""Initial spatial tables

Revision ID: bb1cdaf04930
Revises: 
Create Date: 2026-03-11 11:26:56.282358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'bb1cdaf04930'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('closure_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('closure_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_closure_zones_geom', 'closure_zones', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_closure_zones_id'), 'closure_zones', ['id'], unique=False)
    op.create_geospatial_table('route_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('route_geom', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('profile_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_route_history_route_geom', 'route_history', ['route_geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('safety_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_safety_zones_geom', 'safety_zones', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_safety_zones_id'), 'safety_zones', ['id'], unique=False)
    op.create_geospatial_table('scenic_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gvi_score', sa.Float(), nullable=True),
    sa.Column('park_coverage', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_scenic_segments_geom', 'scenic_segments', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_scenic_segments_id'), 'scenic_segments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenic_segments_id'), table_name='scenic_segments')
    op.drop_geospatial_index('idx_scenic_segments_geom', table_name='scenic_segments', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('scenic_segments')
    op.drop_index(op.f('ix_safety_zones_id'), table_name='safety_zones')
    op.drop_geospatial_index('idx_safety_zones_geom', table_name='safety_zones', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('safety_zones')
    op.drop_geospatial_index('idx_route_history_route_geom', table_name='route_history', postgresql_using='gist', column_name='route_geom')
    op.drop_geospatial_table('route_history')
    op.drop_index(op.f('ix_closure_zones_id'), table_name='closure_zones')
    op.drop_geospatial_index('idx_closure_zones_geom', table_name='closure_zones', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('closure_zones')
    # ### end Alembic commands ###
